#Spawn baby zombie villagers
spawnBabyZombieVillagers = false
#Spawn baby husks
spawnBabyHusks = false
#Spawn baby zombie pigmen
spawnBabyPigmen = false
#Spawn baby drowned
spawnBabyDrowned = false
#Prevent all baby hostile mobs from spawning (for compatibility with modded mobs)
preventHostileBabies = true

