
[origins]

	[origins."origins-classes:nitwit"]
		enabled = true

	[origins."origins:enderian"]
		enabled = true
		"origins:throw_ender_pearl" = true
		"origins:water_vulnerability" = true
		"origins:pumpkin_hate" = true
		"origins:extra_reach" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true

	[origins."origins:human"]
		enabled = true

	[origins."origins-classes:lumberjack"]
		enabled = true
		"origins-classes:tree_felling" = true
		"origins-classes:more_planks_from_logs" = true

	[origins."origins:feline"]
		enabled = true
		"origins:fall_immunity" = true
		"origins:sprint_jump" = true
		"origins:velvet_paws" = true
		"origins:nine_lives" = true
		"origins:weak_arms" = true
		"origins:scare_creepers" = true
		"origins:cat_vision" = true

	[origins."origins-classes:warrior"]
		enabled = true
		"origins-classes:more_attack_damage" = true
		"origins-classes:less_shield_slowdown" = true

	[origins."origins:elytrian"]
		enabled = true
		"origins:elytra" = true
		"origins:launch_into_air" = true
		"origins:aerial_combatant" = true
		"origins:light_armor" = true
		"origins:claustrophobia" = true
		"origins:more_kinetic_damage" = true

	[origins."origins:shulk"]
		enabled = true
		"origins:shulker_inventory" = true
		"origins:natural_armor" = true
		"origins:strong_arms" = true
		"origins:strong_arms_break_speed" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true

	[origins."origins-classes:cleric"]
		enabled = true
		"origins-classes:potion_bonus" = true
		"origins-classes:better_enchanting" = true

	[origins."origins-classes:explorer"]
		enabled = true
		"origins-classes:explorer_kit" = true
		"origins-classes:no_sprint_exhaustion" = true

	[origins."origins:merling"]
		enabled = true
		"origins:water_breathing" = true
		"origins:water_vision" = true
		"origins:aqua_affinity" = true
		"origins:swim_speed" = true
		"origins:like_water" = true
		"origins:aquatic" = true
		"origins:conduit_power_on_land" = true
		"origins:air_from_potions" = true

	[origins."origins:phantom"]
		enabled = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:phasing" = true
		"origins:invisibility" = true
		"origins:burn_in_daylight" = true
		"origins:hunger_over_time" = true
		"origins:fragile" = true
		"origins:phantomize_overlay" = true

	[origins."origins-classes:beastmaster"]
		enabled = true
		"origins-classes:tamed_animal_boost" = true
		"origins-classes:tamed_potion_diffusal" = true

	[origins."origins-classes:merchant"]
		enabled = true
		"origins-classes:trade_availability" = true
		"origins-classes:rare_wandering_loot" = true

	[origins."origins:arachnid"]
		enabled = true
		"origins:climbing" = true
		"origins:master_of_webs" = true
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true

	[origins."origins-classes:rancher"]
		enabled = true
		"origins-classes:twin_breeding" = true
		"origins-classes:more_animal_loot" = true

	[origins."origins:blazeborn"]
		enabled = true
		"origins:fire_immunity" = true
		"origins:nether_spawn" = true
		"origins:burning_wrath" = true
		"origins:hotblooded" = true
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:damage_from_snowballs" = true
		"origins:damage_from_potions" = true

	[origins."origins:avian"]
		enabled = true
		"origins:slow_falling" = true
		"origins:fresh_air" = true
		"origins:like_air" = true
		"origins:tailwind" = true
		"origins:lay_eggs" = true
		"origins:vegetarian" = true

	[origins."origins-classes:archer"]
		enabled = true
		"origins-classes:no_projectile_divergence" = true
		"origins-classes:less_bow_slowdown" = true

	[origins."origins-classes:farmer"]
		enabled = true
		"origins-classes:more_crop_drops" = true
		"origins-classes:better_bone_meal" = true

	[origins."origins-classes:miner"]
		enabled = true
		"origins-classes:more_stone_break_speed" = true
		"origins-classes:no_mining_exhaustion" = true

	[origins."origins-classes:blacksmith"]
		enabled = true
		"origins-classes:quality_equipment" = true
		"origins-classes:efficient_repairs" = true

	[origins."origins-classes:cook"]
		enabled = true
		"origins-classes:better_crafted_food" = true
		"origins-classes:more_smoker_xp" = true

	[origins."origins-classes:rogue"]
		enabled = true
		"origins-classes:sneaky" = true
		"origins-classes:stealth" = true
		"origins-classes:stealth_core" = true

	[origins."origins_backgrounds_two:greenwitch"]
		enabled = true
		"origins_backgrounds_two:bonemeal_dry" = true
		"origins_backgrounds_two:bonemeal_wet" = true
		"origins_backgrounds_two:bonecool" = true

	[origins."origins_backgrounds:athlete"]
		enabled = true
		"origins_backgrounds:faster_speed" = true

	[origins."origins_backgrounds:scribe"]
		enabled = true
		"origins_backgrounds:paperbacks" = true

	[origins."origins_backgrounds_two:disenchanter"]
		enabled = true
		"origins_backgrounds_two:remove_curse" = true

	[origins."origins_backgrounds:novice_mage"]
		enabled = true
		"origins_backgrounds:potion_food" = true

	[origins."origins_backgrounds:fresh_face"]
		enabled = true

	[origins."origins_backgrounds_two:miner"]
		enabled = true
		"origins_backgrounds_two:mining_skill" = true

	[origins."origins_backgrounds_two:butcher"]
		enabled = true
		"origins_backgrounds_two:careful_cuts" = true

	[origins."origins_backgrounds:sailor"]
		enabled = true
		"origins_backgrounds:attack_in_ocean" = true

	[origins."origins_backgrounds_two:blacksmith"]
		enabled = true
		"origins_backgrounds_two:presmelted" = true
		"origins_backgrounds_two:better_armor" = true

	[origins."origins_backgrounds:coalminer"]
		enabled = true
		"origins_backgrounds:ore_harvesting" = true

	[origins."origins_backgrounds_two:bounty_hunter"]
		enabled = true
		"origins_backgrounds_two:dead_or_alive" = true
		"origins_backgrounds_two:heads_will_roll" = true
		"origins_backgrounds_two:heads_will_roll_p" = true
		"origins_backgrounds_two:heads_will_roll_s" = true
		"origins_backgrounds_two:heads_will_roll_z" = true

	[origins."origins_backgrounds_two:woodsman"]
		enabled = true
		"origins_backgrounds_two:axemanship" = true
		"origins_backgrounds_two:tin_miner" = true

	[origins."origins_backgrounds_two:pickpocket"]
		enabled = true
		"origins_backgrounds_two:swipe" = true
		"origins_backgrounds_two:suspicion" = true

	[origins."origins_backgrounds:cultist"]
		enabled = true
		"origins_backgrounds:sacrifice" = true

	[origins."origins_backgrounds_two:sentry"]
		enabled = true
		"origins_backgrounds_two:stout_heart" = true
		"origins_backgrounds_two:slow_step" = true

	[origins."origins_backgrounds_two:hunter"]
		enabled = true
		"origins_backgrounds_two:bowmanship" = true

	[origins."origins_backgrounds_two:alchemist"]
		enabled = true
		"origins_backgrounds_two:sommelier" = true

	[origins."origins_backgrounds:guard"]
		enabled = true
		"origins_backgrounds:shield_prowess" = true

	[origins."origins_backgrounds_two:trader"]
		enabled = true
		"origins_backgrounds_two:starting_money" = true
		"origins_backgrounds_two:money_pouch" = true

	[origins."origins_backgrounds:farmhand"]
		enabled = true
		"origins_backgrounds:trusty_hoe" = true

	[origins."origins_backgrounds:soldier"]
		enabled = true
		"origins_backgrounds:swordsmanship" = true

	[origins."origins_backgrounds:fisher"]
		enabled = true
		"origins_backgrounds:cooked_fishes" = true

	[origins."origins_backgrounds:haunted"]
		enabled = true
		"origins_backgrounds:hello_darkness" = true

	[origins."origins_backgrounds:pirate"]
		enabled = true
		"origins_backgrounds:eyepatch" = true

	[origins."origins_backgrounds_two:street_rat"]
		enabled = true
		"origins_backgrounds_two:safe_flesh" = true
		"origins_backgrounds_two:safe_potate" = true

	[origins."origins_backgrounds:acolyte"]
		enabled = true
		"origins_backgrounds:improved_healing" = true

	[origins."origins_backgrounds_two:swashbuckler"]
		enabled = true
		"origins_backgrounds_two:passado" = true

	[origins."origins_backgrounds_two:cook"]
		enabled = true
		"origins_backgrounds_two:sous_chef" = true

	[origins."origins_backgrounds_two:angler"]
		enabled = true
		"origins_backgrounds_two:lucky" = true

	[origins."origins_backgrounds:cryptkeeper"]
		enabled = true
		"origins_backgrounds:graves" = true

	[origins."origins_backgrounds_two:deep_miner"]
		enabled = true
		"origins_backgrounds_two:in_the_depths" = true

	[origins."origins_backgrounds:retainer"]
		enabled = true
		"origins_backgrounds:legacy_sword" = true

	[origins."origins_backgrounds_two:acrobat"]
		enabled = true
		"origins_backgrounds_two:spring_step" = true
		"origins_backgrounds_two:fence_hop" = true

